"""Add is_hallucination column

Revision ID: 3b2aa721a280
Revises: 001
Create Date: 2026-02-06 12:41:00.825704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b2aa721a280'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcriptions', sa.Column('is_hallucination', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcriptions', 'is_hallucination')
    # ### end Alembic commands ###
