"""add_ai_suggestions_to_transcription

Revision ID: c597ca42f8c9
Revises: 3b2aa721a280
Create Date: 2026-02-09 11:36:45.289402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c597ca42f8c9'
down_revision: Union[str, None] = '3b2aa721a280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcriptions', sa.Column('ai_suggestions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcriptions', 'ai_suggestions')
    # ### end Alembic commands ###
