"""add_ai_model_to_transcription

Revision ID: 65ba55930284
Revises: c597ca42f8c9
Create Date: 2026-02-09 12:20:32.310377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65ba55930284'
down_revision: Union[str, None] = 'c597ca42f8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcriptions', sa.Column('ai_model', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcriptions', 'ai_model')
    # ### end Alembic commands ###
